services:
  - type: web
    name: preordercards
    runtime: node
    plan: starter
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATA_DIR
        value: /var/data
      - key: DISCORD_WEBHOOK_URL
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: EMAIL_FROM
        value: "PreorderCards <notifications@preordercards.com>"
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: DISCORD_CHANNEL_ID
        sync: false
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
